apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-port-80
  namespace: backend
spec:
  podSelector:
    matchLabels:
      app: scraper
  policyTypes:
  - Ingress
  ingress:
  - from: []
    ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: nmywrld/ctrlaltelite-scraper:latest
        ports:
        - containerPort: 8015
        env:
        - name: ENV
          value: "production"
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: scraper-service
  namespace: backend
  annotations:
    cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  selector:
    app: scraper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8015
  type: ClusterIP