apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: service-custom-healthcheck
  namespace: service
spec:
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /  