name: Manual Build Light Image

on:
  workflow_dispatch:

jobs:    
  build_lightweight_image:
    name: Build light image and deploy to GCP
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Tag, Push, and Delete Database Image
        run: |
          docker compose build --no-cache database
          docker tag ctrlaltelite-database:latest ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-database:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-database:latest
          docker system prune -a

      - name: Build, Tag, Push, and Delete application Image
        run: |
          docker compose build --no-cache application
          docker tag ctrlaltelite-application:latest ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-application:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-application:latest
          docker system prune -a -f
      
      - name: Build, Tag, Push, and Delete Factcheck Image
        run: |
          docker compose build --no-cache factcheck
          docker tag ctrlaltelite-factcheck:latest ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-factcheck:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-factcheck:latest
          docker system prune -a -f
  
      - name: Build, Tag, Push, and Delete Scraper Image
        run: |
          docker compose build --no-cache scraper
          docker tag ctrlaltelite-scraper:latest ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-scraper:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-scraper:latest
          docker system prune -a -f

      - name: Build, Tag, Push, and Delete Telebot Image
        run: |
          docker compose build --no-cache telebot
          docker tag ctrlaltelite-telebot:latest ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-telebot:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ctrlaltelite-telebot:latest
          docker system prune -a -f
  